:вай: WiFi
:инт: Internet
= Домашняя сеть WiFi. Общие понятия

== Доступ в {инт}. Провайдер

Практически вся информация, отображающаяся на экранах наших устройств, происходит из {инт}.
Доступ в {инт} предоставляет провайдер. Для этого в помещение снаружи прокладывается кабель, пользователю присваивается уникальные логин и пароль. Чтобы начать работать, достаточно подсоединить кабель к компьютеру, имеющему сетевой вход, и ввести ваш логин и пароль.

== Домашняя {вай} сеть для нескольких устройств

Для того, чтобы обеспечить одновременный доступ в {инт} нескольких гаджетов, необходимо организовать беспроводную сеть. Большинство современных гаджетов способны связываться с источниками, предоставляющими доступ в {инт}, по беспроводной сети. В качестве беспроводной точки доступа выступает роутер. Подготовить роутер к работе можно следующим образом:

* подсоединить кабель провайдера к роутеру используя сетевой разъём, предназначенный для сети {инт}
* подключиться к роутеру через один из разъёмов, предназначенных для домашней сети, используя специальный сетевой кабель или, если данная модель поддерживает такую функцию, посредством автоматически созданной роутером беспроводной сети, данные которой указаны на корпусе роутера и 
* зайти на страничку настроек роутера и ввести логин и пароль, предоставленные провайдером
* переименовать или создать новую {вай} сеть присвоив ей имя и пароль
* задать логин и пароль для входа на страничку настроек роутера




